Milestone 1: Basic Project structure
guillainbisimwa/React-Bookstore pull request #1
Opened 2021-04-14 19:00 UTC by guillainbisimwa

In this PR, I have:

- I have installed redux and PropTypes dependencies,
- I have deployed the application to Heroku (#)
- I have added GitHub workflow linters, ESlint and Stylelints

2021-04-14 21:24 UTC, krys2fa requested changes
# Status: Marked as Invalid! ⚠️  
Please note that your Code Review Request is being marked as invalid. 
This is because the repository is not professional as a result of not following the gitflow guidelines in this milestone.

Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

2021-04-15 09:04 UTC, mikenath223 requested changes
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason: 
- Please create a development branch from the main branch and raise the pull request from the setup branch to development not from setup branch to main branch as you did here.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

2021-04-15 14:36 UTC, bellom approved these changes
## Hi Team :clap:

### Voila! You have finished your first React/Redux Project: Milestone 1.

##### You have done wonderfully well, you passed all checklist for this milestone :+1:
 
# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck with your next milestone :slightly_smiling_face:_ 

**Heads-Up:** _Make sure to read the instructions on pathwright carefully before submitting CRR for milestone 2, that way, you will have a high chance of getting your CRR reviewed just once without submitting it for re-review_

**Best,**

**Oluwaseun J. Bello**
**_Slack Handle - @sean bellom_**

2021-04-15 14:36 UTC, bellom commented on src/index.js
> +}
I believe you're aware you can't have this Bookstore component in here.... 😄

2021-04-15 15:04 UTC, merged